name: Railway Bot Scheduler

on:
  schedule:
    - cron: '40 22 * * *'  # Spegnimento 00:40 italiane
    - cron: '0 6 * * *'    # Avvio 08:00 italiane
  workflow_dispatch:       # Permette run manuale

jobs:
  control-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Stop or start bot on Railway
        run: |
          if [ "${{ github.event.schedule }}" = "40 22 * * *" ]; then
            echo "Stopping bot..."
            curl -X POST https://backboard.railway.app/graphql \
              -H "Content-Type:
