on:
  schedule:
    - cron: '40 22 * * *'  # 00:40 italiane (UTC +2)
  workflow_dispatch:

jobs:
  stop-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Stop bot on Railway
        shell: bash
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
        run: |
          curl -X POST https://backboard.railway.app/graphql \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $RAILWAY_TOKEN" \
            -d '{"query":"mutation { stopService(id: \"'"$RAILWAY_SERVICE_ID"'\") }"}'
