name: Weekly Redis Backup

on:
  schedule:
    - cron: '0 7 * * 1'  # Ogni lunedì alle 09:00 italiane
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Redis client
        run: pip install redis

      - name: Create Python backup script
        run: |
          echo "import redis, json, os" > backup.py
          echo "r = redis.Redis.from_url(os.environ['REDIS_URL'], decode_responses=True)" >> backup.py
          echo "count = r.get('fabbio_count')" >> backup.py
          echo "with open('backup_fabbio_count.json', 'w') as f:" >> backup.py
          echo "    json.dump({'fabbio_count': count}, f)" >> backup.py

      - name: Run backup script
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: python3 backup.py

      - name: Commit and push backup
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add backup_fabbio_count.json
          git commit -m "Weekly backup fabbio_count" || echo "No changes to commit"
          git push
